project:
  type: book  
  output-dir: docs

book:
  title: "Business Report: Evaluation of Omaha, NE Bridge Integrity"
  author: "Jack Macfadyen"
  page-footer:
    left: "Copyright 2025, Jack Macfadyen"
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - methods.qmd
    - results.qmd
    - conclusions.qmd
    - references.qmd
  appendices:
    - draft-data-doc.qmd
    - draft-results.qmd
    - draft-intro-conclusions.qmd
    - draft-exec-summary.qmd

bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme: cosmo
    toc: true
    number-sections: false
  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: false



