# Conclusion

The analysis of the Omaha's bridge inventory and infrastructure with the NBI data reveals critical insights into potential bridge failures over the next five years. While the vast majority of bridges in Douglas County are in fair or good condition, 15 bridges (2.9%) exhibit at least one structural component rated as being in "poor condition". These bridges are, on average, the oldest bridges in the Omaha area. These bridges are at a greater risk of collapsing in the near future than bridges with greater structural integrity. A handful of these bridges also have high amounts of traffic, particularly along Highway 75 and conjoined streets. However, they are steps away from more severe ratings (rating \<= 3). This suggests that the immediate risk of a bridge collapse in Omaha is quite low.

Even so, there are still long-term risks. The older a bridge is, the more likely it is to be in worse condition. As years pass, a bride's condition may deteriorate, which could turn a bridge in poor condition to immediate critical condition. Continued monitoring of these bridges to assess their condition is paramount in ensuring they do not collapse. It's a good thing that no bridges are considered critically deficient, but that comes from continued maintenance and proactive investment. Considering the lack of bridges rated below a 4, Douglas County is doing a good job in their investment in infrastructure and prevention of degradation of their bridges.